### PR TITLE
[WIP] Integrate draggable with connectToSortable support

### PR DESCRIPTION
**Pull request by nickschot**
Implementation for draggable/connectToSortable integration.

### CODE REVIEW

**Comment by nickschot** [comment]
This is still a WIP. Added this PR for easier discussion.

**Comment by ToddSmithSalter** [comment]
@nickschot Please rebase this against upstream master and we'll go from there.

**Comment by nickschot** [comment]
Will do!

**Comment by ToddSmithSalter** [comment]
Alright...so we have a few tests to make pass or rewrite.

**Comment by nickschot** [comment]
Yes part of it can be removed if we decide to remove the content mutation from the addon (which is why at least part of the tests fail). 

My next step will be a small example scenario in the dummy app so you can see what exactly I wanted to achieve.

Also I'm not yet sure of the way I'm taking care of the "out" and "over" events. Might be cleaner to implement those as actions (like "moved") instead of options (as they are not options...).

By the way, is it just me or is github making a mess of the comparison view? Old master?

**Comment by ToddSmithSalter** [comment]
I agree with `out` and `over` being handled via actions.

**Comment by ToddSmithSalter** [comment]
@nickschot One change I'd like to see. It looks like you're implementing the `ui-draggable` component as an array rather than a single draggable. `{{ui-draggable}}` should be a single draggable instance, same as how you'd apply it the plugin if you were using only jQuery.

**Comment by nickschot** [comment]
@ToddSmithSalter agreed. I'll do that. Guess it'd be nice if it would support both block and normal form?

**Comment by ToddSmithSalter** [comment]
I would only support block form. The only instance where someone might not, would be a text only draggable item. It would be best to simply `{{yield}}` whatever is passed in the block, text or more. At least it would make for a simple and understandable API.

**Comment by nickschot** [comment]
The connectWith option also works fine by just adding the option.

**Comment by ToddSmithSalter** [comment]
We need an integration test for `ui-draggable` before merging and publishing.

**Comment by nickschot** [comment]
Definitely. Unfortunately I don't have any time until Friday. So if you can wait that long, I can give it a go :)

Also there's still the out/over thing. It's doing console.log's now? It should just be a bindable function/action right? Don't think the addon has to do anything else with it. I currently use those binds to change the appearance of the draggable during drag.

**Comment by nickschot** [comment]
Still a little short on time. I'll try to work it out later this week.

**Review by ToddSmithSalter — APPROVED** [review]
These look swell 👍🏻

**Comment by ToddSmithSalter** [comment]
I'm not sure what the devil is going on with Travis + npm. Will have to peek later.

**Comment by nickschot** [comment]
I'll also update the readme a bit within the weekend

**Pull request merged**
